### ISSUE TITLE
3DS transaction error handle bug

### ISSUE THREAD

**Issue by yakjuly** [recurly/recurly-client-ruby#496] opened 2019-08-23 18:34 UTC
Ruby Client should handle below example error code

https://dev.recurly.com/page/recurly-3d-secure-2-integration-guide#section--step-3-process-the-purchase-response

```
<errors>
  <transaction_error>
    <error_code>three_d_secure_action_required</error_code>
    <three_d_secure_action_token_id>ABCDEFGHIJKL012345</three_d_secure_action_token_id>
    ...
  </transaction_error>
  <transaction href="..." type="credit_card">
    ...
  </transaction>
</errors>
```

**Describe the bug**

```
a = Recurly::Account.find("uuid")
a.billing_info = {token_id: "***", three_d_secure_action_result_token_id: "B-***"}
a.billing_info.save

NoMethodError: undefined method `value' for nil:NilClass
from /Users/yakjuly/.rvm/gems/ruby-2.5.5@rt-business/gems/recurly-2.18.0/lib/recurly/resource.rb:1050:in `block in apply_errors'

```

**To Reproduce**

1. Create a Recurly account
2. Using Recurly.js to generate a billing info recurly_token 
3. Use token_id to create billing info,  receive `Recurly::Transaction::ThreeDSecureError` with `three_d_secure_action_token_id`
4. Return `three_d_secure_action_token_id` to frontend, frontend success pass the test and submit recurly_token and three_d_secure_action_result_token_id to Backend
5. Backend call SDK to create billing info with `token_id`(recurly_token) and `three_d_secure_action_result_token_id`
6. receive NoMethodError

Debug 
```
From: /Users/yakjuly/.rvm/gems/ruby-2.5.5@rt-business/gems/recurly-2.18.0/lib/recurly/resource.rb @ line 1047 Recurly::Resource#apply_errors:

    1038: def apply_errors(exception)
    1039:   @response = exception.response
    1040:   document = XML.new exception.response.body
    1041:
    1042:   if document.root.name == 'error'
    1043:     # Single error is returned from the API
    1044:     attribute_path = document['symbol'].text.split '.'
    1045:     invalid! [attribute_path[1]], document['description'].text
    1046:   else
 => 1047:     binding.pry
    1048:     # Array of errors was returned by the API
    1049:     document.each_element 'error' do |el|
    1050:       attribute_path = el.attribute('field').value.split '.'
    1051:       invalid! attribute_path[1, attribute_path.length], el.text
    1052:     end
    1053:   end
    1054: end

```

```
[1] pry(#<Recurly::Account>)> @response.body
=> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
"<errors>\n" +
"  <error>\n" +
"    <error_code>three_d_secure_action_result_token_mismatch</error_code>\n" +
"    <error_category>hard</error_category>\n" +
"    <merchant_message>Expected token does not match the action that created it.</merchant_message>\n" +
"    <customer_message>An error occurred while processing your transaction. Please contact support.</customer_message>\n" +
"  </error>\n" +
"</errors>\n"
```
[2] pry(#<Recurly::BillingInfo>)> document.to_s
=> "<errors>  <error>    <error_code>three_d_secure_action_result_token_mismatch</error_code>    <error_category>hard</error_category>    <merchant_message>Expected token does not match the action that created it.</merchant_message>    <customer_message>An error occurred while processing your transaction. Please contact support.</customer_message>  </error></errors>"
[3] pry(#<Recurly::BillingInfo>)> exit

**Expected behavior**

SDK should handle 3DS error correctly, I am not sure what `field` should be for 3DS error, maybe consider as a base error?

**Your Environment**

- Which version of this library are you using? 2.18.0
- Which version of ruby are you using? 2.5.5

**Comment by bhelx** [comment] 2019-08-29 19:34
Closing as duplicate of https://github.com/recurly/recurly-client-ruby/issues/489

**Closed by bhelx** 2019-08-29 19:34 UTC
Labels: bug?
