### ISSUE TITLE
When an adjustment type is nil?

### ISSUE THREAD

**Issue by spyrbri** [recurly/recurly-client-ruby#431] opened 2018-11-16 13:13 UTC
In the Recurly docs says:
`The type of adjustment to return: charge or credit.`

https://dev.recurly.com/docs/adjustment-object

In the gem there is a case where type is nil. 

https://github.com/recurly/recurly-client-ruby/blob/1446464b6ae1e4537fee68f657c4a18b9336043a/lib/recurly/adjustment.rb#L60

 When does this happen?

**Comment by aaron-suarez** [comment] 2018-11-16 17:03
@spyrbri That is an excellent question. The easiest demo is if you are creating a new Adjustment object (I'm not sure why you might do this in production, but technically the library allows this):

```ruby
[1] pry(main)> adjustment = Recurly::Adjustment.new
=> #<Recurly::Adjustment accounting_code: nil, created_at: nil, credit_reason_code: nil, currency: "USD", description: nil, discount_in_cents: nil, end_date: nil, origin: nil, original_adjustment_uuid: nil, product_code: nil, proration_rate: nil, quantity: nil, quantity_remaining: nil, revenue_schedule_type: nil, shipping_address_id: nil, start_date: nil, state: nil, tax_code: nil, tax_details: nil, tax_exempt: nil, tax_in_cents: nil, tax_rates: nil, tax_region: nil, tax_type: nil, tax_types: nil, total_in_cents: nil, unit_amount_in_cents: nil, updated_at: nil, uuid: nil>
[2] pry(main)> adjustment.type
=> nil
```

That being said, is the real question whether the API will ever return an adjustment that has a nil type? I'm not sure the answer to that, but in 5 minutes of testing various ways to create an adjustment, I was unable to create on my sandbox site an adjustment that was not either a `charge` or a `credit`. If you're concerned about this, I can dig a little deeper, but I believe that's there because it's technically possible, not because it's supposed to ever be `nil`.

**Comment by aaron-suarez** [comment] 2018-11-19 16:52
This is going to take a little investigating for me to reproduce. If either of you can provide example XML that causes this (and @spyrbri if you can please indicate whether this happens with Webhooks or via an API request, that would help as well).

If there's a problem with an API request, please indicate which method on what type of object causes this behavior. e.g., `adjustment.find 'something'`

I'll do some testing on my own based on the information I have so far and see if we can get to the bottom of this.

**Comment by aaron-suarez** [comment] 2018-11-21 21:19
Ok, just so we're on the same page:

When an adjustment comes in from the API, its root element looks like this, with the attributes `href` and `type`:
```xml
<adjustment href="https://{subdomain}.recurly.com/v2/adjustments/478fee19cca165e7018f9d43dfb8f742" type="charge">
```

Then, the XML parser goes to read that and hits this bit of code:
https://github.com/recurly/recurly-client-ruby/blob/1446464b6ae1e4537fee68f657c4a18b9336043a/lib/recurly/resource.rb#L406-L408

At this point, there should be an attribute called `@type` set on the Adjustment object, which can be read due to the `attr_reader :type` line in the Adjustment class, and it's written via the `inspect` method here:
https://github.com/recurly/recurly-client-ruby/blob/1446464b6ae1e4537fee68f657c4a18b9336043a/lib/recurly/resource.rb#L1027

From what I'm reading based on your latest comment, you're saying that the `type="charge"` is actually set on the root element (adjustment, in this case), but it's not actually being read in by Nokogiri?

It would be nice to verify that the XML does indeed have this attribute, which will rule out the possibility that the API is incorrectly sending these tags without a `type` attribute. Has anyone seen some XML come in without this type attribute, or is it just being missed somehow by the parsing functions?

**Comment by aaron-suarez** [comment] 2018-11-21 21:29
Oh, to investigate further, it would also be helpful to know what versions of the Ruby client and Nokogiri you're using.

**Comment by spyrbri** [comment] 2018-11-22 07:19
> Ok, just so we're on the same page:
> 
> When an adjustment comes in from the API, its root element looks like this, with the attributes `href` and `type`:
> 
> ```
> <adjustment href="https://{subdomain}.recurly.com/v2/adjustments/{uuid}" type="charge">
> ```
> 
> Then, the XML parser goes to read that and hits this bit of code:
> [recurly-client-ruby/lib/recurly/resource.rb](https://github.com/recurly/recurly-client-ruby/blob/1446464b6ae1e4537fee68f657c4a18b9336043a/lib/recurly/resource.rb#L406-L408)
> 
> Lines 406 to 408 in [1446464](/recurly/recurly-client-ruby/commit/1446464b6ae1e4537fee68f657c4a18b9336043a)
> 
>  xml.root.attributes.each do |name, value| 
>    record.instance_variable_set "@#{name}", value.to_s 
>  end 
> At this point, there should be an attribute called `@type` set on the Adjustment object, which can be read due to the `attr_reader :type` line in the Adjustment class, and it's written via the `inspect` method here:
> [recurly-client-ruby/lib/recurly/resource.rb](https://github.com/recurly/recurly-client-ruby/blob/1446464b6ae1e4537fee68f657c4a18b9336043a/lib/recurly/resource.rb#L1027)
> 
> Line 1027 in [1446464](/recurly/recurly-client-ruby/commit/1446464b6ae1e4537fee68f657c4a18b9336043a)
> 
>  string << "##@type" if instance_variable_defined? :@type 
> From what I'm reading based on your latest comment, you're saying that the `type="charge"` is actually set on the root element (adjustment, in this case), but it's not actually being read in by Nokogiri?
> 
> It would be nice to verify that the XML does indeed have this attribute, which will rule out the possibility that the API is incorrectly sending these tags without a `type` attribute. Has anyone seen some XML come in without this type attribute, or is it just being missed somehow by the parsing functions?

First of all the problem is also on invoices where the type attribute is not like 
```
<adjustment href="https://{subdomain}.recurly.com/v2/adjustments/{uuid}" type="charge">
```
It is another attribute. `<type> charge </type>`

From the info we get from production, the instance variable is not set as well. We tried to get it from the instance variable as a fallback for adjustments and invoices but the error still occurs. We will have more info later today.

**Comment by pkopac** [comment] 2018-11-22 08:40
```
nokogiri (1.8.5)
recurly (2.17.3)
```

**Comment by spyrbri** [comment] 2018-11-23 08:42
From our production logging we found out that we receive some invoices that do not have the type element in the xml. So the problem is coming from Recurly. 
We will send a question to Recurly's support. 
Thank you for your help.

**Comment by aaron-suarez** [comment] 2018-11-26 15:43
Thanks for the update. I will close this issue when we've found an answer internally regarding the API behavior.

**Closed** 2018-11-28 22:34 UTC
