### ISSUE TITLE
issue with trying to update the unit_price_in_cents for a subscription

### ISSUE THREAD

**Issue by rloomba** [recurly/recurly-client-ruby#241] opened 2016-05-03 22:33 UTC
I'm running into an issue when I try to update the `unit_price_in_cents` attribute for one of my subscriptions. Here's the code I'm using to update the subscription. I'm manually overriding the plan's `unit_price_in_cents` with the update, however it doesn't seem to be properly updating. When I check the `pending_subscription`, the old `unit_price_in_cents` shows.

```ruby
subscription.update_attributes(
      plan_code: plan_code,
      quantity: new_quantity,
      timeframe: 'renewal',
      subscription_add_ons: [shipping_add_on],
      unit_amount_in_cents: unit_amount_in_cents
    )
```

Here's a log printout of the PUT request.

```
PUT https://sg-test.recurly.com/v2/subscriptions/35e779a128456c19cc9cb34d79876aad
{"accept"=>["application/xml"], "user-agent"=>["Recurly/2.4.8; ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]"], "x-api-version"=>["2.1"], "accept-language"=>["en-US,en;q=0.8"], "accept-encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "authorization"=>["Basic [FILTERED]"], "content-type"=>["application/xml"]}
<subscription><plan_code>sv-7</plan_code><subscription_add_ons><subscription_add_on><add_on_code>sv-7-shipping</add_on_code><unit_amount_in_cents>500</unit_amount_in_cents></subscription_add_on></subscription_add_ons><timeframe>renewal</timeframe></subscription>
```

I think what's happening is the `unit_amount_in_cents` field isn't changing, so so the [xml_keys](https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource.rb#L1047) method is excluding it from the PUT request. When the subscription updates on the backend, it defaults to the plan's `unit_price_in_cents`, which is wrong. Any ideas on how I can fix this for my use case?

**Comment by bhelx** [comment] 2016-05-03 22:44
hey @rloomba 

Happy to have a look. Which version of the library are you using?

**Comment by bhelx** [comment] 2016-05-03 22:45
hey @rloomba 

I'm going to try to reproduce the problem

**Comment by bhelx** [comment] 2016-05-03 22:48
@rloomba I'm a bit confused because I see the `unit_amount_in_cents` in your xml.

...<unit_amount_in_cents>500</unit_amount_in_cents>...

What was the previous value?

**Comment by rloomba** [comment] 2016-05-03 22:53
@bhelx I think that's the `unit_amount_in_cents` for the add on

**Comment by rloomba** [comment] 2016-05-03 22:54
The `unit_amount_in_cents` value for plan code `sv-7` is `1250` and I'm trying to override it with a value of `1225`

**Comment by bhelx** [comment] 2016-05-04 16:28
@rloomba Okay, this seems to be a bug.

Here is how I was able to work around it:

```ruby
subscription = Recurly::Subscription.find '35eb5dca032eac940429434ef6a80c60'

puts subscription

subscription.quantity = 2
subscription.unit_amount_in_cents = 200

subscription.save!

puts subscription
```

I'd suggest you you don't use `update_attributes` for now. I don't know the exact problem yet, but I suspect the attributes are not being marked as dirty before the save.

**Comment by bhelx** [comment] 2016-05-04 16:36
I'm going to follow up on this tonight or tomorrow morning

**Comment by rloomba** [comment] 2016-05-04 16:57
@bhelx thanks for looking into this!

For my use case, I'd like the change to go into effect at the subscription's renewal, hence when I was passing in `timeframe: 'renewal'`.

If I manually save the subscription:

```ruby
subscription.quantity = 2
subscription.unit_amount_in_cents = 200

subscription.save!
```

It looks like it applies the changes now. Any ideas on how I can achieve the renewal behavior?

**Comment by bhelx** [comment] 2016-05-04 17:03
@rloomba I think you just need to use the attr_accessor methods:

```ruby
subscription.quantity = 2
subscription.unit_amount_in_cents = 200
subscription.timeframe = 'renewal'

subscription.save!
```

Let me know if that is not the case.

**Comment by rloomba** [comment] 2016-05-04 17:12
@bhelx that doesn't seem to work
```ruby
 NoMethodError: undefined method `timeframe=' for #<Recurly::Subscription:0x007fe1ae182788>
```

**Comment by bhelx** [comment] 2016-05-04 17:20
Sorry, I'm realizing that is an attribute for the SubscriptionChange and not the Subscription. The `update_attributes` was implicitly creating a SubscriptionChange (which this library does not have a model for). 

I'll take a few minutes to work out the underlying issue and report back.

**Comment by rloomba** [comment] 2016-05-04 17:34
thanks @bhelx! appreciate all the help on this.

**Comment by bhelx** [comment] 2016-05-04 17:49
@rloomba I wrote a test for this and it appears to be passing. Also I am somehow not able to reproduce this anymore. It's possible I was using the same values the first time I reproduced.

Can you run a script like this just to be sure:

```ruby
subscription = Recurly::Subscription.find '35eb5dca032eac940429434ef6a80c60'

new_quantity = 22
new_unit_amount_in_cents = 540

raise "Same values" if subscription.quantity == new_quantity || subscription.unit_amount_in_cents == new_unit_amount_in_cents

subscription.update_attributes(
 quantity: new_quantity,
 unit_amount_in_cents: new_unit_amount_in_cents,
 timeframe: 'renewal'
)

puts subscription
```

**Comment by bhelx** [comment] 2016-05-04 17:50
If that exception is raised then the values are already set on the model

**Comment by bhelx** [comment] 2016-05-04 17:54
Well, it seems like the server is not holding the values even though we are sending them

**Comment by rloomba** [comment] 2016-05-04 17:57
Yeah that's what I was noticing as well :/

**Comment by bhelx** [comment] 2016-05-04 17:58
So are you seeing the correct XML go across now? Is it only the server response? Because I think the server will respond with the old values until the time of renewal.

**Comment by rloomba** [comment] 2016-05-04 18:19
@bhelx I ran your above script, and it's raising an error. The `unit_amount_in_cents` value is the same.

I'm changing the `plan_code`, however for this new plan code, I'd like to **override** the existing `unit_price_in_cents`.

I think this is what's happening:
1. Since the `unit_amount_in_cents` is not changing, it's not marked as dirty, so it's not sent over the server
2. I'm changing the plan code, so when it changes the plan code, it defaults to the `unit_price_in_cents` that is set on the plan because there are no `unit_price_in_cents` sent over.

> Because I think the server will respond with the old values until the time of renewal.
Correct, but we still should be able to call `subscription.pending_subscription` to get details on the new subscription that will go into effect after renewal.

**Comment by bhelx** [comment] 2016-05-04 19:03
Okay, let me make sure I get this. So the real issue is that because the `unit_amount_in_cents` has not changed on the model, it's not sending that value even though it should be because the `plan_code` has switched and you want to override the value on the new plan code?

If that is so, I think we may be able to just override update_attributes on the Subscription model to take this into account.

**Comment by rloomba** [comment] 2016-05-04 19:07
> Okay, let me make sure I get this. So the real issue is that because the unit_amount_in_cents has not changed on the model, it's not sending that value even though it should be because the plan_code has switched and you want to override the value on the new plan code?

Yep exactly!

> If that is so, I think we may be able to just override update_attributes on the Subscription model to take this into account.

Cool that would be awesome, I've got some spare cycles and would be happy to submit a PR if you can point me in the right direction.

**Comment by bhelx** [comment] 2016-05-04 19:13
@rloomba That would be great!

Every model inherits from Resource which has the update_attributes method: https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource.rb#L865

So I would look at overriding it somewHere in here: https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/subscription.rb#L201

You can try to use `super` but you may have to do something more custom. One thing you could try is something like this

```ruby
def update_attributes(attributes = {})
  # find some way to make these all dirty
  # or maybe we want to only do this if the plan changes?
  self.changed_attributes = attributes

  super
end
```

Let me know if you have any issues I'd be happy to help or add some commits.

**Comment by rloomba** [comment] 2016-05-04 19:28
@bhelx cool, I'll give it a shot and let you know if I have any questions

**Comment by bhelx** [comment] 2016-05-06 16:23
Closing with https://github.com/recurly/recurly-client-ruby/pull/242

**Closed by bhelx** 2016-05-06 16:23 UTC
Labels: bug
