### ISSUE TITLE
Recurly::Resource::Invalid: account is invalid error when creating Subscription with valid account

### ISSUE THREAD

**Issue by natonnelier** [recurly/recurly-client-ruby#451] opened 2019-02-18 18:15 UTC
I'm using the following code to create Accounts:

```
account = Recurly::Account.create! account_code: SecureRandom.hex,
          email: current_user.email,
          first_name: current_user.name,
          last_name: current_user.last_name
```

This seems to work fine:

```
(byebug) #<Recurly::Account accept_language: nil, account_code: "203f3f8579b9ad478b8350d767ee8e32", address: #<Recurly::Address address1: nil, address2: nil, city: nil, company: nil, country: nil, first_name: nil, geo_code: nil, last_name: nil, name_on_account: nil, phone: nil, state: nil, zip: nil>, cc_emails: nil, closed_at: nil, company: nil, company_name: nil, created_at: Mon, 18 Feb 2019 18:07:10 +0000, email: "horacio@gmail.com", entity_use_code: nil, exemption_certificate: nil, first_name: "Horacio", has_active_subscription: false, has_canceled_subscription: false, has_future_subscription: false, has_live_subscription: false, has_past_due_invoice: false, has_paused_subscription: false, hosted_login_token: "hsECbhdjp4qxj7t1QL5fo91C9B1Gpj54", last_name: "Polainas", phone: nil, preferred_locale: nil, state: "active", tax_exempt: nil, updated_at: Mon, 18 Feb 2019 18:07:10 +0000, username: nil, vat_location_valid: nil, vat_number: nil>

account.valid? -> true
```

And I am also able to  see the created account in Recurly's Admin Panel.

However, when I try to create a Subscription linked to this Account I get the following Error:

`<Recurly::Resource::Invalid: account is invalid>`

This is the code I use to create the Subscription:

```
Recurly::Subscription.create! plan_code: 'my-plan-code',
          account: { 
            account_code: account.account_code,
            billing_info: { token_id: @token }
          }
```
I'm using `v 2.17` of the gem.

**Comment by aaron-suarez** [comment] 2019-02-18 19:35
We'll take a look and see if we can reproduce. Thank you for reporting the issue!

Also, feel free to contact Recurly support as well if you're having this problem with multiple accounts.

Taking a quick look at the docs, I notice that a `currency` attribute is also required to create a subscription, but your code only includes a `plan_code` and `account`. It's possible the API is returning (or Ruby client is displaying) a misleading error message, and that the actual problem is that you're missing this attribute. If you haven't already, try the following:

```ruby
Recurly::Subscription.create! plan_code: 'my-plan-code',
          account: { 
            account_code: account.account_code,
            billing_info: { token_id: @token }
          },
          currency: "EUR"
```
Obviously, if your site is configured to use a different currency (such as "USD"), swap out the "EUR" for that value,

**Comment by bhelx** [comment] 2019-02-18 19:38
@natonnelier The `Invalid` error comes with a list of params explaining why the request was invalid. Please let us know what those are. Example:

```ruby
begin
  Recurly::Account.create! first_name: 'Testy'
rescue Recurly::Resource::Invalid => e
  puts e.record.errors
end
```

**Comment by natonnelier** [comment] 2019-02-18 20:34
thanks for the comments. Tried with the currency attribute @aaron-suarez but got the same result. (Currency is anyway set as default in the initializer: `Recurly.default_currency = "USD"`)

**Comment by natonnelier** [comment] 2019-02-18 20:41
@bhelx the error is not in `Account.create` but in `Subscription.create`. And this is all i get in `record.errors`: 
`{"account"=>["is invalid"]}`

**Comment by bhelx** [comment] 2019-02-18 20:59
@natonnelier that's pretty strange. Could be a bug but would need to see the xml. Did you know that you can create the account and subscription in the same call?

```
Recurly::Subscription.create! plan_code: 'my-plan-code',
          account: { 
            account_code: SecureRandom.hex,
            email: current_user.email,
            #....
            billing_info: { token_id: @token }
          }
```

As for the error. Could you perhaps log the xml you are seeing from the response? 

To enable logger:
```
Recurly.logger = Logger.new STDOUT
```
You must also run the application with an environment variable `RECURLY_INSECURE_DEBUG` set to `true`.

If you aren't sure how to get that working. Let me know your subdomain and I can check what's happening on our end.

**Comment by natonnelier** [comment] 2019-02-18 21:34
@bhelx I'm not able to make the Logger work. Do you have documentation for it somewhere?
This is our subdomain: _cloudapp-staging_ if you want to check. I'm working in mi local environment now but hitting that subdomain.

**Comment by bhelx** [comment] 2019-02-18 22:04
Sorry, we make it intentionally obscure to enable for security reasons: https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly.rb#L93

This is the response I'm seeing:

```xml
<errors>
  <error field="subscription.account.billing_info.number" symbol="unacceptable_type">is not an accepted card type</error>
</errors>
```

Where are you getting the token from? Is it coming from recurly.js?

**Comment by natonnelier** [comment] 2019-02-18 22:13
yes @bhelx , I followed this docs: [](https://dev.recurly.com/docs/recurly-js-getting-a-token)
Should mention also we split frontend and backend. I generate the token in the frontend and send a request to the api with recurly_token as a param. Is in the api where the requests we are discussing here take place.

**Comment by bhelx** [comment] 2019-02-18 22:24
As far as I can tell, your request looks right. I don't think it's a problem with this library since it appears to be generating the correct xml. I also was not able to reproduce on any of my test sites using the same code and version. I suspect the problem is in your site configuration but will not be able to confirm today. I suggest you email support@recurly.com with your request and response (and link them to this issue). I can ping them as well and follow up in the morning.

**Comment by natonnelier** [comment] 2019-02-18 22:29
will do @bhelx . Thanks

**Comment by bhelx** [comment] 2019-02-20 19:06
@natonnelier not sure if you have reached out to support yet. We have identified an API change here that is causing this problem. A patch is on the way on the API side. I'm gonna close this for now since it's not related to the ruby library, but feel free to keep the discussion going or re-open if you feel like it relates to this library.

**Closed by bhelx** 2019-02-20 19:06 UTC

**Comment by natonnelier** [comment] 2019-02-20 19:28
great, thanks @bhelx 
I assume there is no change required on our side, right?

**Comment by bhelx** [comment] 2019-02-20 20:22
There should not be, but I'll let you know if that changes.
