### ISSUE TITLE
3DS2 Error Handling Issue when submitting the 3DS2 Action Result Token ID

### ISSUE THREAD

**Issue by cfortuner** [recurly/recurly-client-ruby#489] opened 2019-08-06 23:51 UTC
**Describe the bug**

I am receiving an error when sending recurly the 3DS2 Challenge response token: `three_d_secure_action_result_token_id` via  the `BillingInfo.save!` method.

`NoMethodError message undefined method `value' for nil:NilClass exception undefined method `value' for nil:NilClass`

**To Reproduce**

Test card: 4000000000003220 - challenge flow

1) Using the Challenge test card, trigger the 3DS2 Challenge flow and call BillingInfo.save! with the resulting `three_d_secure_action_result_token_id`
```
 billing_info[:three_d_secure_action_result_token_id] = options[:three_d_secure_action_result_token_id]
 acc.billing_info = billing_info
 acc.billing_info.save!
```
2) Notice the following error 
```
NoMethodError message undefined method `value' for nil:NilClass exception undefined method `value' for nil:NilClass
```

This is coming from here:
https://github.com/recurly/recurly-client-ruby/blob/272db3f5dd5258d8f1453bd11c57be11a2b4d52d/lib/recurly/resource.rb#L1049

If possible, please provide example code which we can run to reproduce the bug.
The faster we can reproduce the bug, the faster we can help you.

**Expected behavior**

I expected a Recurly::Transaction::Error to be raised due to the transaction being invalid?

Please let me know if this is the expected behaviour

**Your Environment**

- Which version of this library are you using? 2.17.11
- Which version of ruby are you using? 2.3.0?

**Comment by cfortuner** [comment] 2019-08-07 01:04
Update: 
I printed out the xml document and it shows
```
DOCUMENT <errors>  <error>    <error_code>three_d_secure_action_result_token_mismatch</error_code>    <error_category>hard</error_category>    <merchant_message>Expected token does not match the action that created it.</merchant_message>    <customer_message>An error occurred while processing your transaction. Please contact support.</customer_message>  </error></errors>
```

I have tried resubmitting the same form token and submitting a different form token with the same result.

**Comment by bhelx** [comment] 2019-08-07 16:49
@cfortuner just wanted to let you know we have eyes on this. And thanks for all the detail! I haven't flipped this over to `bug` yet because we are still investigating the issue on the API side. However, after we get a resolution, i might consider making this parsing code more resilient.

**Comment by cfortuner** [comment] 2019-08-07 16:59
@bhelx Thanks for helping out! I'm not entirely sure it's a bug either. 

I think my main concern is that the error I received was a `three_d_secure_action_result_token_mismatch`. Please let me know if this was expected when using the Test Card.

Thanks again!

**Comment by cfortuner** [comment] 2019-08-13 16:39
@bhelx Any update on this? Specifically on my last question about if I should be receiving a `three_d_secure_action_result_token_mismatch` ?

**Comment by ciaran16** [comment] 2019-08-16 13:09
I'm also experiencing this issue, with both the challenge flow and 4000000000003063 (device) fingerprint flow, and the xml had the same `three_d_secure_action_result_token_mismatch` error too

**Comment by cfortuner** [comment] 2019-08-16 21:14
Update + @ciaran16 

I was able to successfully complete purchase by adding the  three_d_secure_action_result_token_id to the billing info in my purchase calls. 

See Docs https://dev.recurly.com/docs/versioning:
CHANGES IN V2.21
```
Changed <billing_info> request format:
Added <three_d_secure_action_result_token_id> tag. Used to indicate the three_d_secure_action_result_token returned by RJS for 3DS2.
```
I'm not sure if the three_d_secure_action_result_token_mismatch was due to a different error but it seems like its working now.

**Comment by cfortuner** [comment] 2019-08-17 23:13
Update: This worked for purchases, but not for saving billing info.

Still getting the 
<error_code>three_d_secure_action_result_token_mismatch</error_code>    

when trying to update billing info.

**Comment by ciaran16** [comment] 2019-08-19 09:55
Thanks @cfortuner, also managed to get this working for purchases but not for billing info.

I've reproduced this using the recurly API directly so I think the only bug with the client library is it doesn't handle this type of error gracefully

**Comment by lauramosher** [comment] 2019-08-19 13:51
@bhelx Any update on getting this working for billing info?

**Comment by ahmadfh** [comment] 2019-08-19 23:10
@bhelx  i am also having **`three_d_secure_action_result_token_mismatch`** when creating a **subscription** or **account**

**Comment by neuronicnobody** [comment] 2019-08-20 20:04
Hi all, 

**Quick update on this issue:**
We've identified the root cause for the token mismatch error and are planning to deploy a patch to resolve it this week. The issue is on the API side, and while it is a valid error code, it is being returned in many cases where it should not.

Separate, but related, the client library isn't handling this specific error in the XML gracefully. We are working with other teams to decide where it will be fixed (i.e client library or API). However, our first priority is to patch the issue where the error is returned erroneously. This should remove the current blocker.

Thanks for your patience as we continue to work through this issue.

**Comment by neuronicnobody** [comment] 2019-08-20 22:59
All,

The patch was just pushed to production and our QA team has verified that they're not seeing the issue. Please feel free to test again and let us know if you're still seeing the issue.

**Comment by bycare** [comment] 2019-08-27 04:59
@bhelx, I am still  getting following error

three_d_secure_action_result_token_mismatch
hard
Expected token does not match the action that created it.
An error occurred while processing your transaction. Please contact support

**Comment by thevasya** [comment] 2019-08-27 12:39
I'm also seeing this issue with my integration. I don't have it with 4000000000003220 (challenge flow) and 4222222222222220 (frictionless flow), these two work well for me. But when I try 4000000000003063 (fingerprint flow), the issue is there.

Let me provide more details on how two different flows work for me:

#### Challenge flow

1. Fill form using `4000000000003220` for card number.
2. Tokenize form via `Recurly.js`, submit data, including token, to my backend.
3. Attempt to save billing info, the only parameter is `token_id` with a token from step 2.
4. Get `Recurly::Transaction::ThreeDSecureError`.
5. Show 3-D Secure form on frontend, click button to make it succeeed, submit data to my backend.
6. Attempt to save billing info with `token_id` and `three_d_secure_action_result_token_id`.
7. Billing info is saved just fine.
8. Attempt to create new subscription (billing info is not attached, only pass `account: { account_code: <code> }`, `plan_code` etc.)
9. Subscription is created just fine.

#### Fingerprint flow

1. Fill form using `4000000000003063` for card number.
2. Tokenize form via `Recurly.js`, submit data, including token, to my backend.
3. Attempt to save billing info, the only parameter is `token_id` with a token from step 2.
4. Billing info is saved just fine.
5. Attempt to create new subscription (billing info is not attached, only pass `account: { account_code: <code> }`, `plan_code` etc.)
6. Get `Recurly::Transaction::ThreeDSecureError`.
7. Show 3-D Secure form on frontend, it gets auto-approved, submit data to my backend.
8. Attempt to save billing info with `token_id` and `three_d_secure_action_result_token_id`.
9. API client throws an error.

The error is the same ``undefined method `value' for nil:NilClass`` as everyone else gets.

As you can see, the difference is that in the first case (challenge flow), I got 3D Secure exception when I was trying to save billing info, but in the second case (fingerprint flow) billing info was saved with no issues and I only got 3D Secure exception when I was trying to create a new subscription.

Gem version: `2.17.11`.

**Comment by r4m** [comment] 2019-08-27 14:04
> All,
> 
> The patch was just pushed to production and our QA team has verified that they're not seeing the issue. Please feel free to test again and let us know if you're still seeing the issue.

Hi is it solve in which gem version? 2.18.0? Thanks

**Comment by PaulGilmartin** [comment] 2019-08-29 08:56
We are currently testing the PSD2 fingerprint/challenge flow via the recurly API. Although I'm using the python client (using the Python client version 2.9.8 and the recurly client API version 2.21), I'm still experiencing similar issues mentioned in this thread:

 We're following the instructions found at https://dev.recurly.com/page/recurly-3d-secure-2-integration-guide , testing using the card number 400000▇▇▇▇▇▇3063 as recommended there. We are experiencing some issues with Step 6: Submit a New Purchase request.*

*We are correctly receiving the three_d_secure_action_result_token_id and we are using it to create the account billing info (python snippet below):*

*billing_info = recurly.BillingInfo(*
*token_id=billing_info_token_id,*
*three_d_secure_action_result_token_id=three_d_secure_action_result_token_id*
*)*
*account.billing_info = billing_info*

*However, upon attempting to save this account, we are met with the following error:*

*<error_code>three_d_secure_action_result_token_mismatch</error_code>*
*merchant_message>Expected token does not match the action that created it.</merchant_message>\n    <customer_message>An error occurred while processing your transaction.*

I have manually checked that the token we're passing in is the correct one, so I don't think we should be seeing this error. I see above that a patch has been released for the ruby client. Has a similar patch been released for the python client? I don't see anything in the release notes. @bhelx

**Comment by vrodic** [comment] 2019-08-29 14:30
The 3D secure flow worked for me previously (tested on 2019-08-08), using Ruby 2.17.11, now it fails in both client versions (2.18 and Ruby 2.17.11), with the 

<error_code>three_d_secure_action_result_token_mismatch</error_code>

It seems to me this is some kind of server-side regression

**Comment by r4m** [comment] 2019-09-09 11:56
@bhelx is there any update? The error is still present and we would not release in production the front/back end updates to be PSD2 compliant with Recurly until the bug is fixed. Thanks

**Comment by walerian777** [comment] 2019-09-11 11:54
Hi @bhelx,
it looks like the issue hasn't been resolved yet.
First of all, we still receive `three_d_secure_action_result_token_mismatch` in unexpected situations.
Additionally, the library is not able to parse the response just like in the OP's case.

Could you provide any ETA on these two problems?

**Comment by sebastienluquet** [comment] 2019-09-13 16:25
Hi, I also encountered "Expected token does not match the action that created it" at some point while testing 3DS2 and manage to understand what I was doing wrong : I was actually submitting a [new](https://github.com/recurly/recurly-js-examples/blob/1c2e3f054936536cd4ebbfe6703fc7ccc38fa46d/api/ruby/app.rb#L47) account_code on second request.

**Comment by bhelx** [comment] 2019-09-13 19:27
@walerian777 I don't think this is related to the original issue. I can't say for sure without seeing your code but you should check against the guide that @thevasya linked. Per the integration guide, please confirm that Account / Billing info details are not changing between requests to the API endpoints when passing in the 3DS Action Result Token'. If you are still finding an issue, please contact our official support channel.

**Closed** 2019-09-13 19:28 UTC
Labels: bug?

**Comment by sebastienluquet** [comment] 2019-09-13 22:22
@bhelx I think that the guide that @thevasya linked should be updated to mention that **Account** / Billing info / credit card token have to match.

I also think that recurly-js-examples can not currently work [at leat ruby one](https://github.com/recurly/recurly-js-examples/blob/1c2e3f054936536cd4ebbfe6703fc7ccc38fa46d/api/ruby/app.rb#L47) since SecureRandom.uuid is called on each request.

As a work around, recurly account code should be pass to /3d-secure/authenticate.html as a param like token_id or action_token_id. Other field like account firstname and lastname should be forwarded to be submitted again... So it would be even better if those data could be unpacked from (three_d_secure_action_result_)token_id too (as billing info are extracted from token_id )

**Comment by bhelx** [comment] 2019-09-13 22:50
Thanks for the feedback @sebastienluquet. We are going to update the guide and the example apps.

**Comment by sebastienluquet** [comment] 2019-09-13 22:57
@bhelx Thank you.
