### ISSUE TITLE
Calling .each on subscriptions does not work

### ISSUE THREAD

**Issue by scsmith** [recurly/recurly-client-ruby#686] opened 2021-04-01 10:12 UTC
ArgumentError:
       wrong number of arguments (given 1, expected 0)

It's not immediately clear why this is happening but it seems like the iterator might be calling << on a resource rather than the `yielder`

A clear and concise description of what the bug is. Please include a full stack trace if available.

```
Create subscription, immediately cancel subscription twice
```

```ruby
recurly_client
  .list_account_subscriptions(account_id: recurly_account_id)
  .each
  .max(&:current_period_started_at)
```

```ruby
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/schema/schema_factory.rb:35:in `block in define_attribute'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:96:in `<<'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:96:in `block (3 levels) in item_enumerator'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:95:in `each'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:95:in `block (2 levels) in item_enumerator'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:108:in `<<'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:108:in `block (2 levels) in page_enumerator'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:104:in `loop'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:104:in `block in page_enumerator'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:94:in `each'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:94:in `each'
# /bundle/ruby/2.7.0/gems/recurly-4.0.1/lib/recurly/pager.rb:94:in `block in item_enumerator'
```

**Your Environment**

- Recurly 4.0.1
- Ruby 2.7

**Comment by scsmith** [comment] 2021-04-01 11:12
This can probably be closed, it does work with a block passed.

```ruby
.max { |a, b| a.current_period_started_at <=> b.current_period_started_at }
```

**Comment by douglasmiller** [comment] 2021-04-01 14:25
Thanks, @scsmith. As you found, this is expected behavior. The `Pager` resources are intended to be passed a block. We will close the issue, but investigate what can be done to support the usage pattern that you initially attempted.

**Closed as completed by douglasmiller** 2021-04-01 14:25 UTC
Labels: bug?
