### ISSUE TITLE
Getting ArgumentError instead of Recurly::Errors::ValidationError

### ISSUE THREAD

**Issue by hkmaly** [recurly/recurly-client-ruby#538] opened 2019-11-28 16:48 UTC
I'm getting ArgumentError instead of Recurly::Errors::ValidationError when I put nil instead of actual value into account's first name.

**To Reproduce**
```
client = EinNews::RecurlyClient.new
opts = {
    :account     => {
        :first_name => nil,
      },
  }
client.create_purchase(body: opts)
```
**Expected behavior**

Recurly::Errors::ValidationError with recurly_error containing details about what's wrong.

**Your Environment**

recurly-3.1.0
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

**Comment by bhelx** [comment] 2019-11-28 17:00
Thanks for reporting @hkmaly. I was able to reproduce the problem. We will start a patch to fix this.

**Comment by bhelx** [comment] 2019-11-28 17:09
@hkmaly Could you confirm the by pulling #539 ?

**Comment by hkmaly** [comment] 2019-11-28 21:44
Well, it's no longer complaining about first_name, but it's now complaining about
```
ArgumentError - Attribute 'account_code' does not exist on request Recurly::Requests::AccountPurchase
```
on my original example (yes, it should be just 'code' ...)

I think that turning off the local validation isn't correct solution, I would expect to change local validation to return Recurly::Errors::ValidationError ...

**Comment by bhelx** [comment] 2019-11-29 00:49
@hkmaly thanks for trying it out!

> I think that turning off all local validation isn't correct solution, I would expect to change local validation to return Recurly::Errors::ValidationError

We have not turned off the client-side validation. The only validation the client does is checking that you have spelled your key names correctly and passed in the correct types. The PR turns off these type-checks just for nil values (since any type can be nil). It's up to the server to validate everything else.

With regards to the ArgumentError, I understand the confusion, however a ValidationError is meant to signal that the request can be fixed by providing some different values or making a call at another time. However, if you send the wrong keys to the server (such as misspelling them or providing `account_code` instead of `code`) no change in your user's input can fix that. It suggests a problem with your code. That's why we chose ArgumentError in this case. It's not meant to be something that is caught and handled, it's meant to blow up your program. I think if we did use one of the errors, it might make sense for it to be a BadRequest error (400). Or maybe we consider creating a special error class for it. I also think some docs explaining this would be good to. What do you think?

Were you able to get a purchase to work? The ruby example here should be a good starting point if you have not: https://developers.recurly.com/api/v2019-10-10/index.html#operation/create_purchase

**Comment by hkmaly** [comment] 2019-11-29 02:46
Hmmm ... true, this explanation for those two errors being different makes sense. I would still think it should be Recurly::Errors::something and not classical ArgumentError - probably special error class. And, yes, it should be mentioned in documentation.
Also, I'm little worried that this kind of errors may start appearing on library upgrade ... although, if the specification wouldn't change in incompatible way it probably shouldn't ...

Regarding if I make it work, not yet, but I'm doing it in quite not-straightforward way and I actually need to make sure all kind of errors will be handled correctly before trying the correct parameters. Like, that account_code was real mistake, but that nil was deliberate attempt to get error.

**Comment by bhelx** [comment] 2019-11-29 03:21
> I would still think it should be Recurly::Errors::something and not classical ArgumentError - probably special error class. And, yes, it should be mentioned in documentation.

Agreed. We will follow up with that change. I also think the message could be more helpful. We do have a "did-you-mean" functionality in these errors but they only show up if the spelling is close to an existing key. Example, suppose you spell `code` as `coode`, you will see this error:

```
/app/clients/ruby/lib/recurly/schema/schema_validator.rb:28:in `block in validate!': Attribute 'coode' does not exist on request Recurly::Requests::AccountPurchase. Did you mean 'code'? (ArgumentError)
```

I think the takeaway is that it should be some kind of Recurly namespaced error and maybe we can provide some more details (like the list of acceptable keys). And we'll add a section to the documentation.

**Comment by hkmaly** [comment] 2019-11-29 12:13
Not only the message could be more helpful, you can also add some fields which would be easier to parse. Like, list of invalid fields (in the request), list of missing (and required) fields ... wait. It currently stops at first problem doesn't it? Does it need to?

**Comment by hkmaly** [comment] 2019-11-29 15:13
And speaking about documenting errors, getting Recurly::Errors::InvalidTokenError when using token "hello" is not surprising, but I don't see it in documentation either.

**Closed** 2019-12-02 14:53 UTC
Labels: V3, bug
